apiVersion: v2
name: hello-cicd
description: Reusable app chart — pure implementation. Environments live OUTSIDE this chart (see ../../environments/).
type: application
version: 0.1.0          # bump when TEMPLATES change (not on release promotion)
appVersion: "1.0"
