apiVersion: v1
kind: Service
metadata:
  name: hello-cicd
  namespace: {{ .Values.env.namespace }}
  labels:
    app: hello-cicd
    environment: {{ .Values.env.name }}
spec:
  selector:
    app: hello-cicd
    environment: {{ .Values.env.name }}
  ports:
    - { name: http, port: 80, targetPort: 8080 }
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-cicd
  namespace: {{ .Values.env.namespace }}
  labels:
    app: hello-cicd
    environment: {{ .Values.env.name }}
spec:
{{- if .Values.route.host }}
  host: {{ .Values.route.host }}
{{- end }}
  to: { kind: Service, name: hello-cicd }
  port: { targetPort: http }
  tls: { termination: edge, insecureEdgeTerminationPolicy: Redirect }
