# Pool MUST be a CIDR that won't conflict with EC2 ENIs or AWS-assigned IPs.
# In our AWS lab the cluster VPC is 10.0.0.0/16 and we carve out 10.0.10.0/24.
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: rae-pool
  namespace: metallb-system
  annotations:
    # Wave 10: after the MetalLB CR itself is healthy (which deploys the
    # actual MetalLB controllers and speakers in the cluster).
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  addresses:
    - 10.0.10.0/24
