apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rae-lab-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - 'https://github.com/ratikk/openshift-rae-gitops.git'
  orphanedResources:
    warn: false
