---
apiVersion: v1
kind: Namespace
metadata:
  name: vault-system
  labels:
    # Enables Prometheus scraping from the openshift-monitoring stack once
    # we add a ServiceMonitor. Vault exposes Prometheus metrics natively.
    openshift.io/cluster-monitoring: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
